### ISSUE TITLE
How to use this in Yii2

### ISSUE THREAD

**Issue by Global90** [meysampg/intldate#3] opened 2017-06-21 10:08 UTC
How to use this in Yii2

i have error: **Using $this when not in object context**.
```

<?php
namespace app\components;
use meysampg\intldate\IntlDateTrait;

class General extends Component
{
    use IntlDateTrait;
public static function jalaliToGregorian($date,$pattern='yyyy/MM/dd')
    {
        echo $date;
        $dateToGre = explode('/',$date);

        echo $this->fromPersian([$dateToGre[0],$dateToGre[1],$dateToGre[2]])->toGregorian('en')->asDateTime($pattern);
    }
}
```

**Comment by meysampg** [comment] 2017-06-21 10:39
If https://github.com/meysampg/yii2-intldatebehavior doesn't help you, easily use `__callStatic` method to create a proxy for this trait (and also all other traits!). Something like this:

```php
<?php                                                                           
                                                                                
namespace app\components;                                                       
                                                                                
use meysampg\intldate\IntlDateTrait;                                            
use yii\base\UnknownMethodException;                                               
                                                                                   
class Date extends Component                                                       
{                                                                                  
    use IntlDateTrait;                                                             
                                                                                   
    public function __callStatic($method, $parameters)                             
    {                                                                              
        $o = new static;                                                           
                                                                                   
        if (method_exists($o, $method)) {                                          
            $o->{$method}($parameters);                                  
            return $o;
        }                                                                          
                                                                                   
        throw new UnknownMethodException("Method $method not found!");             
    }                                                                              
} 
```
(I don't tested the above code. I just write it as an idea but it may have some errors on running which are not hard to fix).
Now you can use this trait on anywhere you want, for example in your code:
```php
<?php
namespace app\components;

use app\components\Date;

class General extends Component
{
    public static function jalaliToGregorian($date,$pattern='yyyy/MM/dd')
    {
        echo $date;
        $dateToGre = explode('/',$date);

        echo Date::fromPersian([$dateToGre[0],$dateToGre[1],$dateToGre[2]])->toGregorian('en')->asDateTime($pattern);
    }
}
```

**Comment by Global90** [comment] 2017-06-21 13:30
i fix with this code but i have small proble,

1395/03/31 => result: 2017/06/**20**

why 20??
21 is correct

how to fix this

```
class General extends Component
{
    use IntlDateTrait;
    public static function jalaliToGregorian($date,$pattern='yyyy/MM/dd')
    {
        echo $date;
        $dateToGre = explode('/',$date);
        $general = new General();
        echo $general->fromPersian([$dateToGre[0],$dateToGre[1],$dateToGre[2]])->toGregorian('en')->asDateTime($pattern);
    }
}
```

**Comment by meysampg** [comment] 2017-06-22 06:33
I will check it!

**Comment by Global90** [comment] 2017-06-23 18:20
fixed bug?

**Comment by meysampg** [comment] 2017-06-24 14:17
> fixed bug?

Sorry! I'm really busy! I try to fix it til Monday!

**Comment by meysampg** [comment] 2017-07-03 07:56
Can you check it again to ensure the problem is fixed for you or not? @Global90

**Comment by meysampg** [comment] 2017-07-06 13:12
I close this issue. If the problem is consistent please report it. Thanks! @Global90

**Closed as completed by meysampg** 2017-07-06 13:12 UTC
Labels: bug, help wanted
